main/urls.py
from django.urls import path

from .views import *

app_name = 'main'
urlpatterns = [
    path('accounts/register/activate/<str:sign>/', user_activate, name='register_activate'),
    path('account/register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('account/register/', RegisterUserView.as_view(), name='register'),
    path('accounts/login/', BBLoginView.as_view(), name='login'),
    path('accounts/profile/', profile, name='profile'),
    path('account/logout/', BBLogoutView.as_view(), name='logout'),
    path('account/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('account/password/change/', BBPasswordChangeView.as_view(), name='password_change'),
    path('<str:page>/', other_page, name='other'),
    path('', index, name='index')
]

samplesite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('bboard/', include('bboard.urls')),
]

templates/layout/basic.html
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=l, shrink-to-fit=no">
        <title>
            {% block title %}
                Главная - доска объявлений
            {% endblock %}
        </title>
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}">
    {% bootstrap_javascript jquery='slim' %}
    </head>
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
   <body class="container-fluid">
        <header class="mЬ-4">
            <h1 class="display-1 tехt-сеntеr">Объявления</h1>
        </header>
        <div class="row">
            <ul class="col nav justify-content-end border">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:register' %}">Регистрация</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button"
                    aria-expanded="false">Профиль</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'main:profile' %}">Мои объявления</a>
                        <a class="dropdown-item" href="{% url 'main:profile_change' %}">Изменить личные данные</a>
                        <a class="dropdown-item" href="{% url 'main:password_change' %}">Изменить пароль</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'main:logout' %}">Выйти</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Удалить</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'main:login' %}">Вход</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <div class="row">
            <nav class="col-md-auto nav flex-column border">
                <a class="nav-link root" href="{% url 'main:index' %}">Главная</a>
                <a class="nav-link root" href="{% url 'main:other' page='about' %}">О сайте</a>
                <span class="nav-link root font-weight-bold">Недвижимость</span>
                <a class="nav-link" href="#">Жилье</a>
                <a class="nav-link" href="#">Склады</a>
                <a class="nav-link" href="#">Гаражи</a>
                <span class="nav-link root font-weight-bold">Транспорт</span>
                <a class="nav-link" href="#">Легковой</a>
                <a class="nav-link" href="#">Грузовой</a>
            </nav>
            <section class="col border py-2">
                {% bootstrap_messages %}
                {% block content %}
                
                {% endblock %}
            </section>
        </div>
        <footer class="mt-3">
            <p class="text-right font-italic">&copy; Малыхин Я.Л. 2019г.</p>
        </footer>
    </body>
</html>